### ISSUE TITLE
code release?

### ISSUE THREAD

**Issue by akk-123** [VamosC/CapHuman#1]
will you release code?

**Comment by VamosC** [comment]
Thanks for your interest in our work. We'll release the code after refactoring.

**Comment by drdsgvo** [comment]
I would also be interested in the code

**Comment by VamosC** [comment]
🙏 We plan to release the code and checkpoint by the end of this month.

**Comment by akk-123** [comment]
@VamosC It’s April 10th now, when will release code?

**Comment by VamosC** [comment]
> @VamosC It’s April 10th now, when will release code?

@akk-123 We sincerely apologize for the delay. The code is still under review, and we will strive to release it as soon as possible.

**Comment by VamosC** [comment]
🎉 Finally, we release the code and checkpoint. Feel free to ask me any questions.
