### ISSUE TITLE
Question about the training data

### ISSUE THREAD

**Issue by kevendai** [VamosC/CapHuman#10]
Can you please provide /celeba/Full_align_sup_mask/mask/index.npy or tell me how to get it? I found that the cropping method of CelebA-Dialog in the source dataset is different from CelebAMask-HQ, so the bbox of CelebA-Dialog can't be used directly, and the face cropping part in CelebAMask-HQ is resized, so it can't be matched to compare to label the full body image. I would appreciate if you can provide this part of data!

**Comment by VamosC** [comment]
Hi @kevendai , we provide an example below.

full_image: 
![000001_full](https://github.com/user-attachments/assets/72276955-cfed-4ddc-ae10-73fcf7f39f23)

full_mask:
[000001_full_mask.npy.zip](https://github.com/user-attachments/files/17968011/000001_full_mask.npy.zip)

full_mask_vis:
![000001_full_mask_vis](https://github.com/user-attachments/assets/1b12cd9f-f795-4853-b717-37628627952f)

face_image:
![000001_face](https://github.com/user-attachments/assets/254b9350-7f03-4b8d-9b57-058faf03bf5e)

face_mask:
[000001_face_mask.npy.zip](https://github.com/user-attachments/files/17968015/000001_face_mask.npy.zip)

face_mask_vis:
![000001_face_mask_vis](https://github.com/user-attachments/assets/c2302fe0-1d71-4cc5-8fc5-dd5bc7b7b9b2)

id_feature:
[000001.pt.zip](https://github.com/user-attachments/files/17968016/000001.pt.zip)

text prompt:
[000001.json](https://github.com/user-attachments/files/17968018/000001.json)

**Comment by kevendai** [comment]
Thank you so much for providing the example and the method for obtaining the mask. It has been incredibly helpful to me. However, based on the example you shared, I have a few follow-up questions.
I would like to ask how you performed the image preprocessing in your paper. Specifically, you mentioned that:
> For data preprocessing, we crop and resize the image to the size of 512 × 512 resolution. Following [23], we crop and align the face region for the reference image. 
[23] A style-based generator architecture for generative adversarial networks.

Using the original image (000001.jpg) and applying the method described in your referenced paper, I obtained the following result:

![000001](https://github.com/user-attachments/assets/d9ad9a82-9345-4182-ad5f-bc12ddef008c)

However, the result seems to differ from the example you provided, and I noticed some inconsistencies when I looked at the cropped data in the source dataset, as shown below:

![000001](https://github.com/user-attachments/assets/b08a2619-6196-4f2c-8a5e-bf61ddad0e31)

Additionally, I compared the data obtained by cropping using the bounding box provided in the dataset CelebA-Dialog, and the result looks like this:

![img](https://github.com/user-attachments/assets/86ccfd4e-1308-47bc-9792-24d3d57ec7f3)

![crop_img](https://github.com/user-attachments/assets/7fd2f01a-dabb-4d44-aa50-31ca48713e60)

In addition to the full_image, which I’m not entirely sure how you obtained, I would also like to understand how you cropped and aligned the face_image. If you could kindly provide the full dataset used in your experiments, I would greatly appreciate it. I understand this might be a large request, so if it’s not possible, any additional guidance you can offer would be extremely valuable. Feel free to share via Google Drive, Baidu Netdisk, or any other cloud platform you prefer. Thank you so much for your time and help!

**Comment by VamosC** [comment]
Hi @kevendai,

The image preprocessing steps include: (1) in-the-wild image -> (2) 512 x 512 full_image (capturing face and body) -> (3) 512 x 512 face image (focus on the face area).

1. (1) -> (2): **First**, we resize the in-the-wild image where smaller edge of the image is 512, and detect the bounding box of the face.  **Then**, we randomly crop the 512 x 512 area and make sure that the face is included.
2. (2) -> (3): We crop the face area and perform face alignment. For more details, please refer to the [code](https://github.com/adobe-research/diffusion-rig/blob/main/scripts/align.py).
3. We enhance all the images with [CodeFormer](https://github.com/sczhou/CodeFormer).

We hope these can help you.

**Comment by kevendai** [comment]
Thank you so much for the detailed explanation! I really appreciate your clear breakdown of the image preprocessing steps.
