### ISSUE TITLE
How to achieve multi-human generation

### ISSUE THREAD

**Issue by silence-tang** [VamosC/CapHuman#2]
Hi, this is an amazing and elegant work, and it inspired me a lot. May I ask how did you achieve the multi-human generation, that is, how to combine several head conditions and id conditions together then inject into the denoising process? Thank you!

**Comment by VamosC** [comment]
Thanks! For multi-human generation, we get the feature map for each (id, head condition) pair separately. Then, the feature maps are fused and added to the original latent feature map.

**Comment by VamosC** [comment]
For the multi-human generation, we provide an example for two persons. Please refer to `gradios/gradio_visualization_two_person.py` for more details.
