### ISSUE TITLE
Question about training set up.

### ISSUE THREAD

**Issue by 838959823** [VamosC/CapHuman#3]
Are the reference image and GT image during training from the same image of CelebA?

**Comment by VamosC** [comment]
@838959823 

Hi, thanks for reaching out.

Yes, the reference image and the GT image originate from the same image of CelebA. The key difference is that the reference image is cropped to focus only on the face area, while the GT image shows the full body. We provide an example below.

Reference image:
![reference_image](https://github.com/VamosC/CapHuman/assets/26076544/79492705-7871-4e35-807f-8c1bff1a6996)

GT image:
![GT_image](https://github.com/VamosC/CapHuman/assets/26076544/5da8f6ec-bcb2-450b-a73f-ed2d205bfaa0)
