### ISSUE TITLE
How to specify args.control_ckpt and where to download the ckpt

### ISSUE THREAD

**Issue by silence-tang** [VamosC/CapHuman#8]
Hi, may I ask how to specify args.control_ckpt and where to download the ckpt?

**Comment by VamosC** [comment]
You can download the checkpoint from https://huggingface.co/lllyasviel/ControlNet-v1-1/resolve/main/control_v11p_sd15_openpose.pth and put it in the ckpts. Then args.control_ckpt will be ckpts/control_v11p_sd15_openpose.pth. Note that you should also specify args.controlnet_strength > 0.
Please refer to the [updated README.md](https://github.com/VamosC/CapHuman?tab=readme-ov-file#with-openpose-controlnet) for more details and examples.
