### ISSUE TITLE
Question about the training code

### ISSUE THREAD

**Issue by DaiZhewei** [VamosC/CapHuman#9]
Hello author! 
I would like to ask where is the code for the training stage and the Generalizable Identity Preservation section, 
looking forward to your reply, thanks!

**Comment by DaiZhewei** [comment]
I find that the code is based on 3D face generation. If I want to modify the "Encode global and local identity features" and the alignment steps for 2D image generation, is it feasible? Do you have any suggestions? Thank you very much!

**Comment by VamosC** [comment]
Thanks for reaching out! For the training code, check out train.py. Note that we preprocess the data to obtain the ID features and normal/albedo/rendered images. For the ID features preprocessing, you can refer to https://github.com/VamosC/CapHuman/blob/4c735f7180527057a7acc375261a810b43337a06/inference.py#L190-L193 For the alignment steps, you can refer to https://github.com/VamosC/CapHuman/blob/4c735f7180527057a7acc375261a810b43337a06/inference.py#L60

**Comment by DaiZhewei** [comment]
Thank you very much for your reply!
In the paper the CapFace module is trainable, so I was a bit confused about where to train that module in the training code.

**Comment by VamosC** [comment]
3D reconstruction and rendering are fixed. A pretrained face recognition model extracts the global ID feature, while a CLIP image encoder extracts the local ID feature. These features are then processed through two trainable linear layers. Besides, the control model is trainable. You can find more details in the code.

https://github.com/VamosC/CapHuman/blob/4c735f7180527057a7acc375261a810b43337a06/src/cldm/cldm.py#L564-L580

https://github.com/VamosC/CapHuman/blob/4c735f7180527057a7acc375261a810b43337a06/src/cldm/cldm.py#L446-L457

https://github.com/VamosC/CapHuman/blob/4c735f7180527057a7acc375261a810b43337a06/src/cldm/cldm.py#L468-L475

https://github.com/VamosC/CapHuman/blob/4c735f7180527057a7acc375261a810b43337a06/src/cldm/cldm.py#L487

https://github.com/VamosC/CapHuman/blob/4c735f7180527057a7acc375261a810b43337a06/src/cldm/cldm.py#L25

**Comment by DaiZhewei** [comment]
Thank you very much for your reply. I will do further research. 
Wishing you a pleasant day!
